server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop04:3306/atguigu?serverTimezone=UTC
    username: root
    password: 1234
  application:
    name: test
  log4j:
    rootLogger: DEBUG,com.Console,com.File
    logger: com.com.dao=error,com.Console,com.File

  #Console  控制台输出
  log4j.appender.com.Console=org.apache.log4j.ConsoleAppender
  log4j.appender.com.Console.layout=org.apache.log4j.PatternLayout
  log4j.appender.com.Console.layout.ConversionPattern=%d [%t] %-5p [%c] - %m%n

  #File   输出到文件
  #log4j.appender.com.File = org.apache.log4j.FileAppender
  #log4j.appender.com.File.File = D://log2.log
  #log4j.appender.com.File.layout = org.apache.log4j.PatternLayout
  #log4j.appender.com.File.layout.ConversionPattern =%d [%t] %-5p [%c] - %m%n

  #DailyRollingFile  每日滚动输出到文件，昨天的文件名字会变成log3.log.2019-12-13
  log4j.appender.com.File=org.apache.log4j.DailyRollingFileAppender
  log4j.appender.com.File.file=D://log/log.log
  log4j.appender.com.File.DatePattern=.yyyy-MM-dd
  log4j.appender.com.File.layout=org.apache.log4j.PatternLayout
  log4j.appender.com.File.layout.ConversionPattern=%d [%t] %-5p %c [%L] - %m%n

#RollingFile  滚动输出到文件，这里是按照达到多大时切一个文件
#log4j.appender.com.File = org.apache.log4j.RollingFileAppender
#log4j.appender.com.File.file = D://log4.log
#log4j.appender.com.File.MaxFileSize=1KB
#log4j.appender.com.File.MaxBackupIndex=3
#log4j.appender.com.File.layout = org.apache.log4j.PatternLayout
#log4j.appender.com.File.layout.ConversionPattern =%d [%t] %-5p [%c] - %m%n